### PR TITLE
Clean up

### LINKED ISSUE #144: Code clean-up and readability
### User story
As an interested developer or team member, I want to be able to easily find what I am looking for in a code document, so that I can understand the intention.

### Acceptance criteria
There are changes made to the code files that make them more readable.
Redundancies are removed.

### LINKED ISSUE #146: Car, Headset buttons turn green without an active socket
As an user I want the GUI to clearly display when devices are connected and ready to use.

Acceptance criteria: Car and Headset buttons indicate when devices are ready for use.

### PR DESCRIPTION
**Pull request by livmari**
This branch is for cleaning up the final product code files for readability and to remove redundancies.

### CODE REVIEW

**Comment by livmari** [comment]
@ZJW-92 @matekd @dojodj : Why are `int msg` in `goLeft()` and `goForwardLeft()` both 8? Same question for `goRight()` and `goForwardRight()` in MainActivity.java?

Doesn't that mean that these methods are duplicates and do not actually take the car -45 and +45 degrees nav?

**Comment by matekd** [comment]
goLeft() and goRight should send 7 and 3 to turn on the spot. I do not remember if that works with the car though (the tank steering).

**Comment by livmari** [comment]
Ready for review, but please keep in mind that the changes have only been tested in the virtual environment as I don't have an android phone. It shouldn't matter though because I haven't written anything new, only cleaned up the code structure.

**Comment by ZJW-92** [comment]
It's my typing mistakes, I will correct msg for goLeft() and goRight()

**Comment by livmari** [comment]
@ZJW-92 alright :) they’re located directly in the switch case now because I felt like extra methods was a redundancy.

**Comment by livmari** [comment]
@ZJW-92 you can probably get away with making the edit in this branch directly on GitHub because it’s only two characters :)

**Comment by livmari** [comment]
@ZJW-92 could you review now that you've updated? :)

**Review by ZJW-92 — APPROVED** [review]

**Pull request merged**
