### PR TITLE
Bug fixing

### LINKED ISSUE #41: Connectivity issue when car switches from reverse to forward and vice versa
At the moment the car is being controlled via bluetooth. Whenever we order the car to change the car.setSpeed() value from 50 to -50 the car drives backwards for a few seconds then connection is lost. We are assuming the cause to this issue is because of the gap between 50 and -50 is to great and causes some unhandled errors that crashes the blueetooth connection. 

Solution 1
We should try to figure out the threshold for the car and then increase the gap gradually from there. 
Solution 2
Set up a WiFi server and connect through that, hopefully the connection is more stable.

### LINKED ISSUE #73: Car can turn on the spot
### User story
As a driver, I want to be able make the car turn without moving forwards or backwards so that I can maneuver tight corners.

### Acceptable criteria
The car must be able to turn clockwise continuously when holding down the right steering button and counter-clockwise when holding down the left steering button.

### PR DESCRIPTION
**Pull request by matekd**
Added a delay before changing the speed from positive to negative and vice versa. Code should be tested on the car before merge, delays might need to change depending on the testing.

### CODE REVIEW

**Review by AnnanLao — COMMENTED** [review]
what will happen if change speed method does not have a delay function_

**Review by AnnanLao — APPROVED** [review]
what will happen if change speed method does not have a delay function_

**Comment by matekd** [comment]
> what will happen if change speed method does not have a delay function_

It would halt the car very briefly then set the new speed. The delay ensures that the cars motors can handle the change, it does need to be tested and calibrated though.

**Comment by Simonster1999** [comment]
I'll test this code tomorrow probably, unless someone is at campus today.

**Pull request merged**
