### PR TITLE
App backend directions and connections

### PR DESCRIPTION
**Pull request by AnnanLao**

### CODE REVIEW

**Comment by livmari** [comment]
Is the findViewById(R.id.backBtn); refering to the xml tag id? Cause in that case these are named differently than in my files.
Adjust and I'll accept the review :)

**Comment by RuthgerD** [comment]
May I suggest not merging generated javadoc files? It looks quite odd (10k+ line commit) and is unwanted in most cases, I recommend creating a separate branch for these kinds of things :+1:

**Comment by AnnanLao** [comment]
Thank you Ruthger for the comment.

**Comment by AnnanLao** [comment]
> Is the findViewById(R.id.backBtn); refering to the xml tag id? Cause in that case these are named differently than in my files.
> Adjust and I'll accept the review :)

Yes I saw in the xml they are named right, left, osv... I will change accordingly.

**Pull request closed without merging**
